### ISSUE TITLE
Unsure how to install manually to Hass (HASS-OS on Raspberry Pi4)

### ISSUE THREAD

**Issue by gravymaker17** [Legomaniac/hass_lacrosse_alerts_mobile#2]
Terribly sorry to post here if not appropriate, plesae delete if so.

I’m super interested in this integration but can’t seem to understand how to get it working for my HomeAssistant OS on a RaspberryPi (non-docker setup, if that matters?)

I followed the instructions:

1,  I placed the files into /config/custom_components/lacrosse_alerts_mobile/
2.  I added this to my configuration.yaml
```
  sensor:
    - platform: lacrosse_alerts_mobile
      id: !secret lacrosse_id
```
Updated secrets.yaml with:
`lacrosse_id: <16 digit id number from back of unit>`
But when I test the configuration, HomeAssistant complains with:
Platform error sensor.lacrosse_alerts_mobile - Integration 'lacrosse_alerts_mobile' not found.

I also tried adding the git location as a custom repository as in HACS, but I get:
`Integration Legomaniac/hass_lacrosse_alerts_mobile Repository structure for master is not compliant`

Again, apologies for bumping the old thread, just wanted to check to see if others have tried or if its just my HomeAssistant rookie colours showing 

Thanks!
Scott

**Comment by Legomaniac** [comment]
Hey Scott!

Happy to see some interest in this project! I haven't touched it in over a year and my Home Assistant instance hasn't had this data for longer than that.

However, @xninjax just made a pull request I approved a few days ago, so you're not the only interested party! Maybe they could help out, if it's working now for them?

I want to dig back into this, but realistically I'm not going to have the time until late this month.

**Comment by gravymaker17** [comment]
Hey James!  Thanks for this, really appreciate the work you've done to date - and I'm happy to help with any testing if you or @xninjax need some help, or a different environment whenever you dig back into this.  In the meantime I'll start brushing up on my HomeAssitant integration knowledge!     Let me know if I should close this "issue", as its really not an issue, I just wasn't sure were to ask!

Take care, Scott

**Comment by ryar27** [comment]
Hello, I was excited to find this as I still have many lacrosse alert sensors which would be wonderful if integrated into Home Assistant.  I am running into the same issue as gravymaker17 above and bumped into this thread.  Thank you for your work on this, I hope you can get it up and running without too much trouble!

**Comment by gravymaker17** [comment]
There's a link on Home Assistant forums that helped me get it going - check out [this thread] https://community.home-assistant.io/t/working-on-lacrossealertsmobile-com-component-receive-object-has-no-attribute-error-on-start/105014/23
